
@echo off
echo Building the application...
echo Compiling TypeScript...
npx tsc --noEmit false --outDir dist
echo Copying public assets...
xcopy public\* dist\ /E /I /Y
echo Copying CSS files...
xcopy src\*.css dist\ /Y
echo Build completed!
pause
